[FIX] connector_importer: source consumer mixin
Traceback:
```
  File ".../connector_importer_source_sftp/components/event_listeners.py", line 32, in _skip_move_file
    source = importer.recordset.get_source()
  File ".../connector_importer/models/sources/source_consumer_mixin.py", line 71, in get_source
    return self.source_ref_id
  File "/opt/odoo/odoo/fields.py", line 1303, in __get__
    self.compute_value(recs)
  File "/opt/odoo/odoo/fields.py", line 1485, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/odoo/models.py", line 5297, in _compute_field_value
    fields.determine(field.compute, self)
  File "/opt/odoo/odoo/fields.py", line 110, in determine
    return needle(*args)
  File ".../connector_importer/models/sources/source_consumer_mixin.py", line 43, in _compute_source_ref_id
    item.source_ref_id = f"{item.source_model},{item.source_id}"
  File "/opt/odoo/odoo/fields.py", line 1398, in __set__
    self.write(protected_records, value)
  File "/opt/odoo/odoo/fields.py", line 1205, in write
    cache_value = self.convert_to_cache(value, records)
  File "/opt/odoo/odoo/fields.py", line 3041, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for import.recordset.source_ref_id: 'import.source.csv.sftp,1'
```

For some reason I don't know, by the time the event listener skip_if condition is
evaluated, the `import.recordset` model does not have applied the override to
`_selection_source_ref_id` in the mixin, and so the Reference field fails with
this ValueError.

The workaround here makes `get_source` not actually use the Reference field, but
directly `source_model` and `source_id`, which of course do not attempt to
validate the value.